# environment.yml  – final, no source build
name: dia-tts
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  # … same conda packages as before …

  - pip:
      # pull PyTorch & Torchaudio cu118 wheels
      - --extra-index-url https://download.pytorch.org/whl/cu118
      - torch==2.6.0+cu118
      - torchaudio==2.6.0+cu118

      # 👉 *only* wheel version that exists for cp310/cu118
      - flash-attn==2.5.2.post1+cu118

      # rest of your pip-only packages
      - gradio>=5.25.2
      - descript-audio-codec>=1.0.0
      - ffcv
      - ctc-forced-aligner
      - cut-cross-entropy
      - "triton==3.2.0; sys_platform == 'linux'"
      - "triton-windows==3.2.0.post18; sys_platform == 'win32'"
