name: dia-tts
channels:
  - conda-forge
dependencies:
  # ── core interpreter ─────────────────────────────────────────
  - python=3.11
  - pip                        # enables the pip: section

  # ── conda-available runtime libs ────────────────────────────
  - numpy>=2.2.4
  - pydantic>=2.11.3
  - safetensors>=0.5.3
  - pysoundfile>=0.13.1
  - huggingface_hub>=0.30.2
  - polars
  - transformers
  - peft
  - wandb
  - ninja>=1.11.1.4
  - packaging>=25.0

  # ── pip-only packages (GPU stack + extras) ──────────────────
  - pip:
      # --- CUDA 11.8 PyTorch stack ------------------------------------------
      - --extra-index-url https://download.pytorch.org/whl/cu118
      - torch==2.6.0+cu118
      - torchaudio==2.6.0+cu118

      # --- ready-made Flash-Attention wheel (cu118) -------------------------
      - flash-attn==2.7.4.post1+cu118

      # --- rest of Dia’s deps ----------------------------------------------
      - gradio>=5.25.2
      - descript-audio-codec>=1.0.0
      - ffcv
      - ctc-forced-aligner
      - cut-cross-entropy
      - "triton==3.2.0; sys_platform == 'linux'"
      - "triton-windows==3.2.0.post18; sys_platform == 'win32'"
