name: dia-tts
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - pytorch=2.6.0
  - torchaudio=2.6.0
  - pytorch-cuda=12.6  # [linux] CUDA 12.6 support (GPU)
  - numpy>=2.2.4
  - pydantic>=2.11.3
  - safetensors>=0.5.3
  - pysoundfile>=0.13.1    # SoundFile for audio I/O (libsndfile)
  - huggingface_hub>=0.30.2
  - gradio>=5.25.2
  - ninja>=1.11.1.4
  - packaging>=25.0
  - polars        # DataFrame library
  - transformers  # Hugging Face Transformers
  - peft          # Parameter-Efficient Fine-Tuning
  - wandb         # Weights & Biases logging
  - pip           # Include pip to install packages not on conda
  - pip:
      - descript-audio-codec>=1.0.0
      - flash-attn              # FlashAttention (optimized attention)
      - ffcv                    # Fast loader library
      - ctc-forced-aligner      # CTC Forced Alignment tool
      - cut-cross-entropy       # Memory-efficient cross-entropy loss
      - "triton==3.2.0; sys_platform == 'linux'"
      - "triton-windows==3.2.0.post18; sys_platform == 'win32'"
